/* Lyrics Sync Studio 4.0. Local lyrics editor; no network requests. */
(() => {
'use strict';
const C=globalThis.LyricSyncCore, $=id=>document.getElementById(id), audio=$('audio');
const PREFIX='zerosu-lyrics-only-v1:project:', ACTIVE='zerosu-lyrics-only-v1:active';
const OLD_PREFIX='zerosu-lyrics-sync-v2:project:', OLD_ACTIVE='zerosu-lyrics-sync-v2:active';
const TAB=C.uid('tab'), MAX_AUDIO=120*1024*1024, MAX_EMBED=40*1024*1024;
let project=C.fresh(), dirty=false, conflict=false, undoStack=[], redoStack=[];
let activeFile=null, audioUrl=null, audioReady=false, loading=false, audioToken=0;
let peaks=null, raf=0, lastFrame=0, toastTimer=0, loopEnd=null, fastDone=false;
let editingId=null, pendingSubtitle=null, lyricsSignature='', storageNote='';
const current=()=>project.rows.find(r=>r.id===project.editor.selectedRowId)||null;
const index=()=>project.rows.findIndex(r=>r.id===project.editor.selectedRowId);
const el=(tag,props={},text)=>{const node=document.createElement(tag);Object.assign(node,props);if(text!==undefined)node.textContent=text;return node;};
function say(message,error=false){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').classList.toggle('error',error);$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,error?6500:2600);}
function safeSelection(){if(!current())project.editor.selectedRowId=project.rows[0]?.id??null;}
function persist(){
  if(conflict){$('autosave').textContent='다른 탭 변경 감지 · 사본으로 계속하세요.';return false;}
  try{localStorage.setItem(PREFIX+project.projectId,JSON.stringify({project,dirty,writer:TAB}));localStorage.setItem(ACTIVE,project.projectId);storageNote='자동 복구 저장 · 음원 제외';$('autosave').textContent=storageNote;return true;}
  catch(e){storageNote='자동 저장 불가 · 프로젝트 JSON을 저장하세요.';$('autosave').textContent=storageNote;return false;}
}
function checkpoint(){undoStack.push(JSON.stringify(project));while(undoStack.length>50 || (undoStack.length>1&&undoStack.reduce((n,s)=>n+s.length,0)>4_000_000))undoStack.shift();redoStack=[];}
function commit(structural=false){project.updatedAt=new Date().toISOString();dirty=true;safeSelection();persist();render(structural);}
function undo(){if(!undoStack.length)return;redoStack.push(JSON.stringify(project));project=JSON.parse(undoStack.pop());fastDone=false;commit(true);say('직전 변경을 취소했습니다.');}
function redo(){if(!redoStack.length)return;undoStack.push(JSON.stringify(project));project=JSON.parse(redoStack.pop());fastDone=false;commit(true);say('변경을 다시 적용했습니다.');}
function flush(){const node=document.activeElement;if(node===$('projectTitle')||node?.matches('.row-times input'))node.blur();}
function detachAudio(){audioToken++;audio.pause();audio.removeAttribute('src');audio.load();if(audioUrl)URL.revokeObjectURL(audioUrl);audioUrl=null;activeFile=null;audioReady=false;loading=false;peaks=null;loopEnd=null;fastDone=false;cancelAnimationFrame(raf);$('waveNote').textContent='음원을 선택하면 파형이 표시됩니다.';}
function abandon(){flush();if(dirty&&!confirm('아직 파일로 저장하지 않은 변경이 있습니다. 다른 작업으로 전환할까요?\n취소 후 프로젝트 JSON을 저장할 수 있습니다.'))return false;if(!persist()&&!conflict&&project.rows.length&&!confirm('자동 저장이 되지 않았습니다. 파일을 저장하지 않았다면 작업을 잃을 수 있습니다. 계속할까요?'))return false;return true;}
function install(p,isDirty=false){detachAudio();project=p;dirty=isDirty;conflict=false;$('conflict').hidden=true;undoStack=[];redoStack=[];safeSelection();persist();render(true);}
function renderRows(force=false){
  const signature=project.rows.map(r=>[r.id,r.text,r.section].join('\0')).join('\u0001');
  if(force||signature!==lyricsSignature){lyricsSignature=signature;const fragment=document.createDocumentFragment();
    for(const [i,row] of project.rows.entries()){
      const item=el('article',{className:'lyric-row'});item.dataset.id=row.id;
      const select=el('button',{className:'select-row'});select.dataset.select=row.id;select.setAttribute('aria-label',(i+1)+'번 가사 선택: '+row.text);
      const copy=el('span',{className:'row-copy'});copy.append(el('span',{className:'row-section'},row.section),el('span',{className:'row-text'},row.text));
      select.append(el('span',{className:'row-number'},String(i+1).padStart(2,'0')),copy);
      const times=el('div',{className:'row-times'});
      for(const [key,name] of [['start','시작'],['end','종료']]){const label=el('label',{},name+' (초)');const input=el('input',{type:'number',min:'0',step:'0.001',inputMode:'decimal',placeholder:'—'});input.dataset.id=row.id;input.dataset.field=key;input.setAttribute('aria-label',(i+1)+'번 '+name+' 시간 (초)');label.append(input);times.append(label);}
      const edit=el('button',{className:'edit-row'},'수정');edit.dataset.edit=row.id;edit.setAttribute('aria-label',(i+1)+'번 가사 수정');
      item.append(select,times,edit);fragment.append(item);
    }
    $('rows').replaceChildren(fragment);
  }
  const lookup=new Map(project.rows.map(r=>[r.id,r]));
  for(const item of $('rows').children){const row=lookup.get(item.dataset.id);item.classList.toggle('active',row.id===current()?.id);item.querySelector('[data-select]').setAttribute('aria-pressed',String(row.id===current()?.id));for(const input of item.querySelectorAll('input')){if(input!==document.activeElement)input.value=row[input.dataset.field]===null?'':row[input.dataset.field].toFixed(3);input.max=String(project.duration??C.LIMIT.seconds);}}
}
function renderDock(){const r=current(),i=index();$('selectionIndex').textContent=r?'선택 '+(i+1)+' / '+project.rows.length+'줄':'선택한 가사';$('currentText').textContent=r?.text||'가사를 입력하면 여기에서 시간을 기록합니다.';$('prev').disabled=!r||i===0;$('next').disabled=!r||i===project.rows.length-1;for(const id of ['start','end','fast'])$(id).disabled=!r||!audioReady||loading;$('fast').replaceChildren(document.createTextNode(fastDone?'마지막 종료 ':'연속 기록 '),el('kbd',{},'Enter'));for(const id of ['back','play','forward'])$(id).disabled=!audioReady||loading;updateDockSize();}
function render(force=false){safeSelection();if(document.activeElement!==$('projectTitle'))$('projectTitle').value=project.title;$('speed').value=String(project.editor.playbackRate);$('audioName').textContent=loading?'음원 확인 중…':activeFile?activeFile.name:project.audio.fileName?'↻ 음원 다시 선택':'＋ 음원 선택';$('audioNote').textContent=loading?'파일과 재생 길이를 확인하고 있습니다.':activeFile?'음원·가사는 서버로 전송되지 않습니다.':project.audio.fileName?'원본: '+project.audio.fileName:'MP3 · WAV · M4A 등 브라우저 지원 음원';$('chooseAudio').disabled=loading;$('duration').textContent=C.fmt(project.duration);$('seek').disabled=!audioReady;$('seek').max=String(project.duration||1);$('empty').hidden=project.rows.length>0;$('undo').disabled=!undoStack.length;$('redo').disabled=!redoStack.length;
  const issues=C.validate(project),issueIds=new Set(issues.map(e=>e.rowId)),complete=project.rows.filter(r=>r.start!==null&&r.end!==null&&r.end>r.start&&!issueIds.has(r.id)).length;
  $('progress').textContent=complete+' / '+project.rows.length+'줄 완료';$('progressBar').style.width=(project.rows.length?complete/project.rows.length*100:0)+'%';$('issuesBox').hidden=!issues.length;$('issuesSummary').textContent='시간 확인 '+new Set(issues.map(e=>e.rowId)).size+'줄 · 펼쳐서 확인';$('issues').replaceChildren(...issues.slice(0,100).map(issue=>{const b=el('button',{},issue.message);b.onclick=()=>{selectRow(issue.rowId,true);};return b;}));
  renderRows(force);const invalid=new Set(issues.filter(e=>e.code!=='missing').map(e=>e.rowId));for(const input of $('rows').querySelectorAll('input'))input.classList.toggle('invalid',invalid.has(input.dataset.id));
  for(const id of ['export','shiftTimes','fillEnds','resetTiming'])$(id).disabled=!project.rows.length;$('listen').disabled=!audioReady||current()?.start==null;$('clearTiming').disabled=!current();renderDock();tick();
}
function updateDockSize(){if(matchMedia('(max-width:760px)').matches)document.documentElement.style.setProperty('--dock-height',$('syncDock').getBoundingClientRect().height+'px');}
function selectRow(id,scroll=false){if(!project.rows.some(r=>r.id===id))return;project.editor.selectedRowId=id;fastDone=false;loopEnd=null;persist();render();if(scroll)followSelection();}
function offsetRow(delta){const i=Math.max(0,Math.min(project.rows.length-1,index()+delta));if(project.rows[i])selectRow(project.rows[i].id,true);}
function followSelection(){const row=Array.from($('rows').children).find(e=>e.dataset.id===current()?.id);if(!row)return;const rect=row.getBoundingClientRect();const bottom=matchMedia('(max-width:760px)').matches?$('syncDock').getBoundingClientRect().top:innerHeight;if(rect.top<10||rect.bottom>bottom-10)row.scrollIntoView({block:'center',behavior:'auto'});}
function stamp(kind,continuous=false){flush();const row=current(),i=index();if(!audioReady||!row||loading)return;const t=C.round(Math.max(0,Math.min(project.duration,audio.currentTime)));if(kind==='end'&&(row.start===null||t<=row.start))return say('시작을 먼저 기록하고 그보다 늦은 시각에 종료를 찍으세요.',true);
  checkpoint();row[kind]=t;if(continuous&&i>0){const prev=project.rows[i-1];if(prev.start!==null&&prev.end===null&&prev.start<t)prev.end=t;}
  const advance=kind==='end'||continuous;if(advance&&i<project.rows.length-1)project.editor.selectedRowId=project.rows[i+1].id;fastDone=continuous&&i===project.rows.length-1;loopEnd=null;commit();if(advance)followSelection();say((i+1)+'번 '+(kind==='start'?'시작':'종료')+' '+C.fmt(t)+' 기록');
}
function fast(){if(fastDone){stamp('end');}else stamp('start',true);}
function seek(t){if(!audioReady)return;loopEnd=null;audio.currentTime=Math.max(0,Math.min(project.duration,t));tick();}
async function play(){if(!audioReady||loading)return;loopEnd=null;if(audio.paused){if(audio.currentTime>=project.duration)audio.currentTime=0;try{await audio.play();}catch(e){say('재생 버튼을 다시 누르거나 지원되는 음원을 선택하세요.',true);}}else audio.pause();}
function tick(){if(loopEnd!==null&&!audio.paused&&audio.currentTime>=loopEnd){audio.pause();loopEnd=null;}const time=audioReady?audio.currentTime:0;$('clock').textContent=C.fmt(time);$('dockClock').textContent=C.fmt(time);if(document.activeElement!==$('seek'))$('seek').value=String(time);$('play').textContent=audio.paused?'▶ 재생':'Ⅱ 정지';const active=new Set(project.rows.filter(r=>r.start!==null&&r.end!==null&&time>=r.start&&time<r.end&&audioReady).map(r=>r.id));for(const row of $('rows').children)row.classList.toggle('playing',active.has(row.dataset.id));drawWave();}
function animate(time){if(time-lastFrame>=40){tick();lastFrame=time;}if(!audio.paused)raf=requestAnimationFrame(animate);}
function metadata(target,url){return new Promise((resolve,reject)=>{let timer;const cleanup=()=>{clearTimeout(timer);target.removeEventListener('loadedmetadata',ok);target.removeEventListener('error',bad);};const ok=()=>{cleanup();if(!Number.isFinite(target.duration)||target.duration<=0||target.duration>C.LIMIT.seconds)reject(Error('음원 길이는 0초 초과, 24시간 이하여야 합니다.'));else resolve(target.duration);};const bad=()=>{cleanup();reject(Error('이 브라우저에서 음원을 읽지 못했습니다. 지원되는 MP3·WAV 등으로 다시 선택하세요.'));};target.addEventListener('loadedmetadata',ok);target.addEventListener('error',bad);timer=setTimeout(()=>{cleanup();reject(Error('음원을 읽는 데 시간이 너무 오래 걸립니다. 다시 선택하세요.'));},15000);target.src=url;target.load();});}
async function loadAudio(file){
  if(!file)return;if(!file.size||file.size>MAX_AUDIO)return say('음원은 0바이트 초과, 120 MiB 이하여야 합니다.',true);
  const token=++audioToken,pid=project.projectId,expected=C.clone(project.audio),oldDuration=project.duration;
  const probe=document.createElement('audio');probe.preload='metadata';const url=URL.createObjectURL(file);let adopted=false;loading=true;render();
  try{const duration=C.round(await metadata(probe,url));if(token!==audioToken||pid!==project.projectId)return;
    let hash=null;if(crypto.subtle&&(expected.sha256||file.size<=MAX_EMBED)){const buffer=await file.arrayBuffer();hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',buffer)),x=>x.toString(16).padStart(2,'0')).join('');}
    if(token!==audioToken||pid!==project.projectId)return;
    const mismatch=expected.fileName&&(expected.fileName!==file.name||expected.size!==null&&expected.size!==file.size||oldDuration!==null&&Math.abs(oldDuration-duration)>0.1||expected.sha256&&hash&&expected.sha256!==hash);
    if(mismatch&&!confirm('기존 음원과 파일명·크기·길이 또는 내용이 다릅니다.\n현재 가사 시간을 그대로 유지하고 이 음원을 사용할까요? 새 노래는 새 작업으로 시작하세요.'))return;
    audio.pause();if(audioUrl)URL.revokeObjectURL(audioUrl);audioReady=false;activeFile=null;peaks=null;loopEnd=null;fastDone=false;
    await metadata(audio,url);if(token!==audioToken||pid!==project.projectId){audio.removeAttribute('src');audio.load();return;}
    audioUrl=url;adopted=true;activeFile=file;audioReady=true;project.duration=duration;project.audio={fileName:file.name,size:file.size,type:file.type,lastModified:file.lastModified,sha256:hash};audio.playbackRate=project.editor.playbackRate;undoStack=[];redoStack=[];dirty=true;project.updatedAt=new Date().toISOString();persist();$('waveNote').textContent='파형 생성 중…';render();void makeWave(file,token);say('음원을 연결했습니다. 재생하며 시간을 기록하세요.');
  }catch(e){if(token===audioToken)say(e.message,true);}
  finally{probe.removeAttribute('src');probe.load();if(!adopted)URL.revokeObjectURL(url);if(token===audioToken){loading=false;render();}}
}
async function makeWave(file,token){if(file.size>MAX_EMBED||project.duration>1200){$('waveNote').textContent='큰 음원은 파형 없이 재생·시간 기록을 지원합니다.';drawWave();return;}let ctx;try{const AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx)throw Error('Web Audio 미지원');ctx=new AudioCtx();const buffer=await ctx.decodeAudioData(await file.arrayBuffer());const samples=buffer.getChannelData(0),bins=800,result=new Float32Array(bins),stride=Math.max(1,Math.ceil(samples.length/bins));for(let i=0;i<bins;i++){let max=0;for(let j=i*stride;j<Math.min(samples.length,(i+1)*stride);j+=Math.max(1,Math.floor(stride/150)))max=Math.max(max,Math.abs(samples[j]));result[i]=max;}if(token!==audioToken)return;peaks=result;$('waveNote').textContent='파형을 탭하면 해당 시각으로 이동합니다.';drawWave();}catch(e){if(token===audioToken){$('waveNote').textContent='파형 없이 재생·시간 기록을 사용할 수 있습니다.';drawWave();}}finally{if(ctx)try{await ctx.close();}catch(e){}}}
function drawWave(){const canvas=$('wave'),width=Math.max(1,Math.round(canvas.clientWidth*devicePixelRatio)),height=Math.max(1,Math.round(canvas.clientHeight*devicePixelRatio));if(canvas.width!==width)canvas.width=width;if(canvas.height!==height)canvas.height=height;const ctx=canvas.getContext('2d');if(!ctx)return;ctx.clearRect(0,0,width,height);const duration=project.duration||1,row=current();if(row&&row.start!==null&&row.end!==null&&row.end>row.start){ctx.fillStyle='#d9e9d0';ctx.fillRect(row.start/duration*width,0,(row.end-row.start)/duration*width,height);}ctx.strokeStyle='#719569';ctx.lineWidth=Math.max(1,devicePixelRatio);ctx.beginPath();if(peaks){for(let i=0;i<peaks.length;i++){const x=i/peaks.length*width,y=peaks[i]*height*.43;ctx.moveTo(x,height/2-y);ctx.lineTo(x,height/2+y);}}else{ctx.moveTo(0,height/2);ctx.lineTo(width,height/2);}ctx.stroke();if(audioReady){const x=audio.currentTime/duration*width;ctx.strokeStyle='#a77228';ctx.lineWidth=2*devicePixelRatio;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,height);ctx.stroke();}}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type})),link=el('a',{href:url,download:name});document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function saveProject(){flush();project.updatedAt=new Date().toISOString();download(C.filename(project.title)+'_Sync_Project.json',JSON.stringify({...project,savedAt:new Date().toISOString()},null,2),'application/json;charset=utf-8');dirty=false;persist();say('프로젝트 JSON을 저장했습니다. 음원도 별도로 보관하세요.');}
function normalizeImport(raw,name){return C.normalize(raw,name.replace(/(?:_Sync_Project)?\.json$/i,''));}
function decodeBundle(raw){if(raw.format!=='zerosu-lyrics-bundle'||![1,2].includes(raw.version))throw Error('지원하지 않는 음원 포함 파일입니다.');const m=raw.media;if(!m||typeof m.name!=='string'||!m.name||m.name.length>500||typeof m.base64!=='string'||!Number.isSafeInteger(m.size)||m.size<=0||m.size>MAX_EMBED)throw Error('내장 음원 형식·용량 오류');if(m.base64.length>Math.ceil(MAX_EMBED/3)*4||m.base64.length%4!==0||!/^[A-Za-z0-9+/]*={0,2}$/.test(m.base64))throw Error('내장 음원 Base64 오류');const binary=atob(m.base64);if(binary.length!==m.size)throw Error('내장 음원 크기가 다릅니다.');if(m.type!=null&&(typeof m.type!=='string'||m.type.length>150))throw Error('내장 음원 유형 오류');const bytes=Uint8Array.from(binary,x=>x.charCodeAt(0));return new File([bytes],m.name,{type:m.type||'',lastModified:m.lastModified||0});}
async function openProject(file){if(!file)return;if(file.size>120*1024*1024)return say('프로젝트 파일은 120 MiB 이하여야 합니다.',true);const pid=project.projectId;try{const raw=JSON.parse((await file.text()).replace(/^\uFEFF/,'')),bundled=raw.format==='zerosu-lyrics-bundle',source=bundled?raw.project:raw,p=normalizeImport(source,file.name);let media=bundled?decodeBundle(raw):null;if(media&&p.audio.size!==null&&p.audio.size!==media.size)throw Error('프로젝트와 내장 음원의 크기가 다릅니다.');if(pid!==project.projectId)return;if(!abandon())return;p.projectId=C.uid('project');install(p,false);if(media)await loadAudio(media);say(source.version===4||source.cues?.length?'가사와 시간을 가져왔습니다. 콘티·영상 큐는 원본 파일에 보관하세요.':media?'음원 포함 프로젝트를 가져왔습니다.':'프로젝트를 열었습니다. 원본 음원을 다시 선택하세요.');}catch(e){say('프로젝트 열기 실패: '+e.message,true);}}
function lyricsPreview(){try{const result=pendingSubtitle?{rows:pendingSubtitle.rows,kept:pendingSubtitle.rows.length,cleared:project.rows.filter(r=>r.start!==null||r.end!==null).length}:C.reconcile(project.rows,$('lyricsText').value);$('lyricsPreview').textContent=pendingSubtitle?'자막 '+result.rows.length+'줄 · 자막의 시간을 함께 가져옵니다. '+pendingSubtitle.warnings.join(' '):'입력 '+result.rows.length+'줄 · 기존 시간 유지 '+result.kept+'줄'+(result.cleared?' · 기존 시간이 바뀌거나 사라지는 '+result.cleared+'줄':'');$('lyricsError').textContent='';$('applyLyrics').disabled=false;}catch(e){$('lyricsError').textContent=e.message;$('applyLyrics').disabled=true;}}
function openLyrics(){flush();audio.pause();loopEnd=null;pendingSubtitle=null;$('lyricsText').value=C.lyricsText(project.rows);$('lyricsError').textContent='';lyricsPreview();$('lyricsDialog').showModal();}
function applyLyrics(){try{const result=pendingSubtitle?{rows:pendingSubtitle.rows,cleared:project.rows.filter(r=>r.start!==null||r.end!==null).length}:C.reconcile(project.rows,$('lyricsText').value);if(result.cleared&&!confirm('기존 시간이 입력된 '+result.cleared+'줄이 삭제되거나 시간이 바뀝니다. 계속할까요?\n문구만 바꾸려면 각 줄의 수정 버튼을 사용하세요.'))return;if(!result.rows.length&&project.rows.length&&!confirm('전체 가사를 지울까요? 실행 취소로 복원할 수 있습니다.'))return;checkpoint();project.rows=result.rows;fastDone=false;loopEnd=null;$('lyricsDialog').close();commit(true);say('가사 '+result.rows.length+'줄을 적용했습니다.');}catch(e){$('lyricsError').textContent=e.message;}}
function openRow(id=null){flush();audio.pause();loopEnd=null;editingId=id;const row=project.rows.find(r=>r.id===id);$('rowHeading').textContent=row?'가사 수정':'한 줄 추가';$('rowText').value=row?.text||'';$('rowSection').value=row?.section||current()?.section||'구간 미지정';$('rowError').textContent='';$('deleteRow').hidden=!row;$('rowDialog').showModal();}
function applyRow(){try{const text=$('rowText').value.trim(),section=$('rowSection').value.trim();if(!text||text.length>C.LIMIT.text||/\n\s*\n/.test(text))throw Error('가사는 2,000자 이내, 내부 빈 줄 없이 입력하세요.');if(!section||section.length>C.LIMIT.section)throw Error('구간 이름은 1~120자로 입력하세요.');if(!editingId&&project.rows.length>=C.LIMIT.rows)throw Error('가사는 최대 1,000줄입니다.');checkpoint();if(editingId){const row=project.rows.find(r=>r.id===editingId);if(row.section!==section){row.section=section;row.sectionId=C.uid('section');}row.text=text;}else{const nearby=current();const row={id:C.uid('lyric'),sectionId:nearby?.section===section?nearby.sectionId:C.uid('section'),section,text,start:null,end:null};project.rows.splice(index()+1,0,row);project.editor.selectedRowId=row.id;}$('rowDialog').close();fastDone=false;commit(true);}catch(e){$('rowError').textContent=e.message;}}
function nudge(sign){flush();const row=current(),key=$('edge').value;if(!row||row[key]===null)return say('먼저 보정할 시간을 기록하세요.',true);const t=C.round(row[key]+Number($('step').value)*sign);if(t<0||t>(project.duration??C.LIMIT.seconds))return say('음원 범위를 벗어나므로 변경하지 않았습니다.',true);checkpoint();row[key]=t;commit();}
function recentEntries(){const entries=[];try{for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(!key.startsWith(PREFIX)&&!key.startsWith(OLD_PREFIX))continue;try{const value=JSON.parse(localStorage.getItem(key));const p=C.normalize(value.project);entries.push({key,project:p,legacy:key.startsWith(OLD_PREFIX),dirty:!!value.dirty});}catch(e){}}}catch(e){say('브라우저 저장소에 접근할 수 없습니다.',true);}return entries.sort((a,b)=>Date.parse(b.project.updatedAt)-Date.parse(a.project.updatedAt)).slice(0,30);}
function listRecent(){flush();persist();$('recentList').replaceChildren(...recentEntries().map(entry=>{const item=el('div',{className:'recent-item'});item.append(el('b',{},entry.project.title),el('small',{},entry.project.rows.length+'줄 · '+new Date(entry.project.updatedAt).toLocaleString('ko-KR')+(entry.legacy?' · 이전 버전':'')));const open=el('button',{},'이 작업 열기');open.onclick=()=>{if(!abandon())return;const p=C.clone(entry.project);p.projectId=C.uid('project');$('recentDialog').close();install(p,entry.dirty||entry.legacy);say('복구본을 열었습니다. 원본 음원을 다시 선택하세요.');};item.append(open);return item;}));if(!$('recentList').children.length)$('recentList').append(el('p',{},'이 브라우저에 저장된 최근 작업이 없습니다.'));$('recentDialog').showModal();}
function onFile(id,callback){$(id).addEventListener('change',async event=>{const file=event.target.files[0];event.target.value='';if(!file)return;try{await callback(file);}catch(e){say(e.message,true);}});}
$('newProject').onclick=()=>{if(!abandon())return;install(C.fresh(),false);say('새 작업을 시작했습니다.');};$('openProject').onclick=()=>{flush();$('projectInput').click();};$('saveProject').onclick=saveProject;$('recentProjects').onclick=listRecent;$('help').onclick=()=>$('helpDialog').showModal();
$('projectTitle').onchange=()=>{const title=$('projectTitle').value.trim();if(!title){$('projectTitle').value=project.title;return;}if(title!==project.title){checkpoint();project.title=title;commit();}};
$('projectTitle').onkeydown=e=>{if(e.key==='Enter'&&!e.isComposing)e.target.blur();};
for(const button of document.querySelectorAll('[data-close]'))button.onclick=()=>$(button.dataset.close).close();
$('chooseAudio').onclick=()=>$('audioInput').click();onFile('audioInput',loadAudio);onFile('projectInput',openProject);
$('chooseAudio').ondragover=e=>{e.preventDefault();e.currentTarget.classList.add('dragover');};$('chooseAudio').ondragleave=e=>e.currentTarget.classList.remove('dragover');$('chooseAudio').ondrop=e=>{e.preventDefault();e.currentTarget.classList.remove('dragover');if(e.dataTransfer.files.length===1)void loadAudio(e.dataTransfer.files[0]);else say('음원은 하나씩 선택하세요.',true);};document.addEventListener('dragover',e=>{if(e.dataTransfer?.types.includes('Files'))e.preventDefault();});document.addEventListener('drop',e=>{if(e.dataTransfer?.types.includes('Files'))e.preventDefault();});
$('bulkLyrics').onclick=openLyrics;$('emptyLyrics').onclick=openLyrics;$('addRow').onclick=()=>openRow();$('loadText').onclick=()=>$('textInput').click();onFile('textInput',async file=>{if(file.size>5_000_000)throw Error('가사·자막 파일은 5MB 이하로 선택하세요.');const text=await file.text();if(!$('lyricsDialog').open)return;const ext=file.name.split('.').pop().toLowerCase();if(['srt','vtt','lrc'].includes(ext)){pendingSubtitle=C.importSubtitles(text,ext);$('lyricsText').value=C.lyricsText(pendingSubtitle.rows);}else{pendingSubtitle=null;$('lyricsText').value=text;}lyricsPreview();});$('lyricsText').oninput=()=>{pendingSubtitle=null;lyricsPreview();};$('applyLyrics').onclick=applyLyrics;$('applyRow').onclick=applyRow;
$('deleteRow').onclick=()=>{if(!editingId||!confirm('이 가사를 삭제할까요? 실행 취소로 복원할 수 있습니다.'))return;checkpoint();project.rows=project.rows.filter(r=>r.id!==editingId);$('rowDialog').close();fastDone=false;commit(true);};
$('rows').onclick=e=>{const select=e.target.closest('[data-select]'),edit=e.target.closest('[data-edit]');if(select)selectRow(select.dataset.select);if(edit)openRow(edit.dataset.edit);};
$('rows').addEventListener('focusin',e=>{if(e.target.matches('input[data-field]')){project.editor.selectedRowId=e.target.dataset.id;fastDone=false;loopEnd=null;renderDock();for(const row of $('rows').children){const selected=row.dataset.id===current()?.id;row.classList.toggle('active',selected);row.querySelector('[data-select]').setAttribute('aria-pressed',String(selected));}persist();}});
$('rows').addEventListener('change',e=>{const input=e.target;if(!input.matches('input[data-field]'))return;const row=project.rows.find(r=>r.id===input.dataset.id),key=input.dataset.field,value=input.value===''?null:Number(input.value);if(input.validity.badInput||value!==null&&(!Number.isFinite(value)||value<0||value>(project.duration??C.LIMIT.seconds))){input.value=row[key]??'';return say('시간은 0~'+(project.duration??C.LIMIT.seconds)+'초 범위로 입력하세요.',true);}const next=value===null?null:C.round(value);if(row[key]===next)return;checkpoint();row[key]=next;commit();});
$('prev').onclick=()=>offsetRow(-1);$('next').onclick=()=>offsetRow(1);$('start').onclick=()=>stamp('start');$('end').onclick=()=>stamp('end');$('fast').onclick=fast;$('play').onclick=play;$('back').onclick=()=>seek(audio.currentTime-3);$('forward').onclick=()=>seek(audio.currentTime+3);$('seek').oninput=()=>seek(Number($('seek').value));$('speed').onchange=()=>{project.editor.playbackRate=Number($('speed').value);audio.playbackRate=project.editor.playbackRate;persist();};
$('wave').onclick=e=>{const rect=$('wave').getBoundingClientRect();seek(Math.max(0,Math.min(1,(e.clientX-rect.left)/rect.width))*(project.duration||0));};$('wave').onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();e.stopPropagation();seek(e.key==='Home'?0:e.key==='End'?project.duration:audio.currentTime+(e.key==='ArrowLeft'?-3:3));}};
$('undo').onclick=undo;$('redo').onclick=redo;$('minus').onclick=()=>nudge(-1);$('plus').onclick=()=>nudge(1);$('clearTiming').onclick=()=>{flush();const row=current();if(!row)return;checkpoint();row.start=row.end=null;fastDone=false;commit();};
$('listen').onclick=async()=>{const row=current();if(!audioReady||row?.start==null)return;audio.currentTime=Math.max(0,row.start-.5);loopEnd=row.end!==null&&row.end>row.start?Math.min(project.duration,row.end+.3):null;try{await audio.play();}catch(e){loopEnd=null;say('음원을 재생하지 못했습니다.',true);}};
$('resetTiming').onclick=()=>{flush();if(!confirm('전체 가사 시간을 지울까요? 실행 취소로 복원할 수 있습니다.'))return;checkpoint();project.rows.forEach(r=>r.start=r.end=null);fastDone=false;commit();};
$('shiftTimes').onclick=()=>{flush();$('shiftError').textContent='';$('shiftDialog').showModal();};$('applyShift').onclick=()=>{try{if(!$('shiftDelta').value.trim()||!$('shiftDelta').validity.valid)throw Error('이동량을 올바른 숫자로 입력하세요.');const scope=$('shiftScope').value,ids=project.rows.filter((r,i)=>scope==='all'||scope==='from'&&i>=index()||scope==='selected'&&r.id===current()?.id).map(r=>r.id);const result=C.shift(project,ids,Number($('shiftDelta').value));checkpoint();project.rows=result.rows;$('shiftDialog').close();commit();say(result.count+'줄의 시간을 이동했습니다.');}catch(e){$('shiftError').textContent=e.message;}};
$('fillEnds').onclick=()=>{flush();const result=C.alignEnds(project,project.rows.map(r=>r.id));if(!result.count)return say('채울 수 있는 종료가 없습니다. 다음 줄의 시작을 먼저 기록하세요.');if(!confirm('비어 있는 종료 '+result.count+'줄을 다음 줄 시작으로 채웁니다. 마지막 줄은 음원 끝을 사용합니다.\n간주와 실제 가창 종료는 직접 확인하세요.'))return;checkpoint();project.rows=result.rows;commit();};
$('export').onclick=()=>{flush();try{const format=$('exportFormat').value;if(format==='lrc'&&project.rows.some(r=>r.text.includes('\n'))&&!confirm('LRC는 가사 내부 줄바꿈을 공백으로 합칩니다. 계속할까요?'))return;const content=format==='csv'?C.csv(project):format==='txt'?C.lyricsText(project.rows):format==='lrc'?C.lrc(project):C.subtitles(project,format);download(C.filename(project.title)+'_Lyrics.'+format,content,format==='csv'?'text/csv;charset=utf-8':format==='vtt'?'text/vtt;charset=utf-8':format==='srt'?'application/x-subrip;charset=utf-8':'text/plain;charset=utf-8');say(format.toUpperCase()+' 파일을 내보냈습니다.');}catch(e){$('issuesBox').open=true;say(e.message,true);}};
$('makeCopy').onclick=()=>{project=C.clone(project);project.projectId=C.uid('project');project.title=(project.title+' (사본)').slice(0,200);project.createdAt=new Date().toISOString();conflict=false;$('conflict').hidden=true;undoStack=[];redoStack=[];commit(true);};
window.addEventListener('storage',e=>{if(e.key!==PREFIX+project.projectId||!e.newValue)return;try{if(JSON.parse(e.newValue).writer!==TAB){conflict=true;$('conflict').hidden=false;persist();}}catch(err){}});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});window.addEventListener('pagehide',persist);window.addEventListener('resize',()=>{updateDockSize();drawWave();});
document.addEventListener('keydown',e=>{if(e.isComposing||e.altKey)return;const key=e.key.toLowerCase(),modifier=e.ctrlKey||e.metaKey;if(document.querySelector('dialog[open]')){if(modifier&&key==='s')e.preventDefault();return;}if(modifier&&key==='s'){e.preventDefault();saveProject();return;}if(e.target.closest('input,textarea,select,[contenteditable="true"]'))return;if(modifier){if(key==='z'){e.preventDefault();e.shiftKey?redo():undo();}else if(key==='y'){e.preventDefault();redo();}return;}if(e.target.closest('button,summary')&&(e.key==='Enter'||e.key===' '))return;const actions={' ':play,s:()=>stamp('start'),e:()=>stamp('end'),Enter:fast,ArrowUp:()=>offsetRow(-1),ArrowDown:()=>offsetRow(1),ArrowLeft:()=>seek(audio.currentTime-3),ArrowRight:()=>seek(audio.currentTime+3)};if(actions[e.key]||actions[key]){e.preventDefault();if(!e.repeat||(e.key==='ArrowLeft'||e.key==='ArrowRight'))(actions[e.key]||actions[key])();}});
audio.addEventListener('play',()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(animate);tick();});audio.addEventListener('pause',()=>{cancelAnimationFrame(raf);tick();});for(const name of ['timeupdate','seeked','ended'])audio.addEventListener(name,tick);audio.addEventListener('error',()=>{if(audioReady){audioReady=false;render();say('음원 재생 오류입니다. 파일을 다시 선택하세요.',true);}});
try{const savedId=localStorage.getItem(ACTIVE),saved=savedId&&localStorage.getItem(PREFIX+savedId);if(saved){const value=JSON.parse(saved);project=C.normalize(value.project);dirty=!!value.dirty;}else{const oldId=localStorage.getItem(OLD_ACTIVE),old=oldId&&localStorage.getItem(OLD_PREFIX+oldId);if(old){const value=JSON.parse(old);project=C.normalize(value.project);project.projectId=C.uid('project');dirty=true;setTimeout(()=>say('이전 작업의 가사·시간을 복원했습니다. 원본 음원을 다시 선택하세요.'),200);}}}catch(e){say('자동 복구본을 읽지 못했습니다. 저장한 JSON을 열어 주세요.',true);}
persist();render(true);if(window.ResizeObserver)new ResizeObserver(updateDockSize).observe($('syncDock'));
})();
