// Run with npm test after npm install and npx playwright install chromium.
// PW_BROWSER_PATH may select an already installed Chromium executable.
const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const assert = require('node:assert/strict');
const {chromium} = require('playwright');
const root = path.resolve(__dirname, '..');
const allowed = new Set(['index.html', 'style.css', 'core.js', 'app.js']);
const types = {html:'text/html; charset=utf-8',css:'text/css; charset=utf-8',js:'application/javascript; charset=utf-8'};
const wav = Buffer.alloc(44 + 16000 * 6 * 2);
wav.write('RIFF',0);wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(16000,24);wav.writeUInt32LE(32000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(wav.length-44,40);
for(let i=0;i<16000*6;i++)wav.writeInt16LE(Math.round(Math.sin(i*2*Math.PI*220/16000)*1200),44+i*2);
const audioFile={name:'test.wav',mimeType:'audio/wav',buffer:wav};
const server=http.createServer((req,res)=>{const name=req.url.split('?')[0].replace(/^\//,'')||'index.html';if(name==='favicon.ico'){res.writeHead(204);res.end();return;}if(!allowed.has(name)){res.writeHead(404);res.end();return;}res.writeHead(200,{'Content-Type':types[name.split('.').pop()]});res.end(fs.readFileSync(path.join(root,name)));});
const errors=[];
async function audio(page){await page.locator('#audioInput').setInputFiles(audioFile);await page.waitForFunction(()=>!document.getElementById('play').disabled);await page.waitForFunction(()=>!document.getElementById('chooseAudio').disabled);}
async function time(page,t){await page.evaluate(t=>{document.getElementById('audio').currentTime=t;},t);await page.waitForFunction(t=>Math.abs(document.getElementById('audio').currentTime-t)<.02,t);}
async function lyrics(page,text='[Verse]\n첫 번째 가사\n두 번째 가사\n[Chorus]\n마지막 가사'){await page.locator('#bulkLyrics').click();await page.locator('#lyricsText').fill(text);await page.locator('#applyLyrics').click();}
async function downloaded(page,button){const wait=page.waitForEvent('download');await page.locator(button).click();const download=await wait;return fs.readFileSync(await download.path(),'utf8').replace(/^\uFEFF/,'');}
async function layout(page,label){const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);assert.equal(overflow,false,label+' horizontal overflow');const dock=await page.locator('#syncDock').boundingBox();const viewport=page.viewportSize();if(viewport.width<=760){assert(dock.y+dock.height<=viewport.height+1,label+' dock below viewport');assert(dock.y>=0,label+' dock above viewport');}for(const id of ['play','start','end','fast']){const box=await page.locator('#'+id).boundingBox();assert(box.width>=44&&box.height>=38,label+' button target '+id);}}
(async()=>{let browser;try{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url='http://127.0.0.1:'+server.address().port+'/';browser=await chromium.launch({headless:true,...(process.env.PW_BROWSER_PATH?{executablePath:process.env.PW_BROWSER_PATH}:{})});
  for(const [label,width,height,mobile] of [['desktop',1366,900,false],['mobile',390,844,true],['small-mobile',320,568,true],['tablet',768,1024,true],['landscape',667,375,true]]){
    const context=await browser.newContext({viewport:{width,height},isMobile:mobile,hasTouch:mobile,acceptDownloads:true});const page=await context.newPage();page.on('pageerror',e=>errors.push(label+': '+e.message));page.on('dialog',dialog=>dialog.accept());page.on('request',req=>{if(!req.url().startsWith(url)&&!req.url().startsWith('blob:'))errors.push('Unexpected external request: '+req.url());});
    await page.goto(url);await layout(page,label);await audio(page);await lyrics(page);await time(page,1);await page.locator('#start').click();await time(page,2);await page.locator('#end').click();await time(page,2.5);await page.locator('#fast').click();await time(page,3.5);await page.locator('#fast').click();assert.match(await page.locator('#fast').textContent(),/마지막 종료/);await time(page,4.5);await page.locator('#fast').click();assert.equal(await page.locator('#progress').textContent(),'3 / 3줄 완료');await layout(page,label);
    const saved=JSON.parse(await downloaded(page,'#saveProject'));assert.deepEqual(saved.rows.map(r=>[r.start,r.end]),[[1,2],[2.5,3.5],[3.5,4.5]]);assert.equal(saved.cues,undefined);assert.equal(saved.storyboard,undefined);
    const srt=await downloaded(page,'#export');assert.match(srt,/00:00:01,000 --> 00:00:02,000/);assert.match(srt,/00:00:03,500 --> 00:00:04,500/);
    await page.locator('#exportFormat').selectOption('vtt');assert.match(await downloaded(page,'#export'),/^WEBVTT/);
    await page.locator('#exportFormat').selectOption('lrc');assert.match(await downloaded(page,'#export'),/\[00:02.500\]두 번째 가사/);
    const endInput=page.locator('.lyric-row').last().locator('input[data-field="end"]');await endInput.fill('2');await endInput.blur();assert(await page.locator('#progress').textContent()!=='3 / 3줄 완료');await page.locator('#export').click();assert.match(await page.locator('#toast').textContent(),/오류/);await page.locator('#undo').click();assert.equal(await page.locator('#progress').textContent(),'3 / 3줄 완료');
    await page.locator('#saveProject').click();await page.reload();assert.equal(await page.locator('.lyric-row').count(),3);assert(await page.locator('#start').isDisabled());assert.equal(await page.locator('.lyric-row').first().locator('input[data-field="start"]').inputValue(),'1.000');await audio(page);
    await page.locator('#play').click();await page.waitForFunction(()=>!document.getElementById('audio').paused);await page.locator('#play').click();assert(await page.evaluate(()=>document.getElementById('audio').paused));
    if(label==='desktop'){
      const old={...saved,version:4,cues:[{unused:'legacy'}],storyboard:{cuts:[{unused:'legacy'}]}};await page.locator('#projectInput').setInputFiles({name:'old-v4.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(old))});await page.waitForFunction(()=>document.getElementById('start').disabled);assert.equal(await page.locator('.lyric-row').count(),3);assert.match(await page.locator('#toast').textContent(),/콘티/);
      const bundle={format:'zerosu-lyrics-bundle',version:2,project:old,media:{name:'test.wav',size:wav.length,type:'audio/wav',base64:wav.toString('base64')}};await page.locator('#projectInput').setInputFiles({name:'legacy.lysync',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bundle))});await page.waitForFunction(()=>!document.getElementById('play').disabled);assert.equal(await page.locator('#progress').textContent(),'3 / 3줄 완료');
      await page.locator('#bulkLyrics').click();await page.locator('#textInput').setInputFiles({name:'import.srt',mimeType:'text/plain',buffer:Buffer.from('1\n00:00:00,500 --> 00:00:01,000\n새 가사\n')});await page.waitForFunction(()=>document.getElementById('lyricsPreview').textContent.includes('자막 1줄'));await page.locator('#applyLyrics').click();assert.equal(await page.locator('.lyric-row').count(),1);assert.equal(await page.locator('.lyric-row input[data-field="start"]').inputValue(),'0.500');await page.locator('#saveProject').click();
      const second=await context.newPage();await second.goto(url);await page.waitForFunction(()=>!document.getElementById('conflict').hidden);await page.locator('#makeCopy').click();assert(await page.locator('#conflict').isHidden());await second.close();
    }
    await page.screenshot({path:path.join(root,'test-results',label+'.png'),fullPage:true});console.log('PASS '+label+' '+width+'x'+height+': timing, exports, restore, playback, responsive layout');await context.close();
  }
  const context=await browser.newContext({viewport:{width:1280,height:800}});const page=await context.newPage();page.on('pageerror',e=>errors.push('keyboard: '+e.message));page.on('dialog',d=>d.accept());await page.goto(url);await audio(page);await lyrics(page,'키보드 첫 줄\n키보드 둘째 줄');await page.locator('.lyrics h2').click();await page.evaluate(()=>document.activeElement.blur());await time(page,1);await page.keyboard.press('s');await time(page,2);await page.keyboard.press('e');await time(page,3);await page.keyboard.press('Enter');await time(page,4);await page.keyboard.press('Enter');assert.equal(await page.locator('#progress').textContent(),'2 / 2줄 완료');await page.keyboard.press('Control+z');assert.notEqual(await page.locator('#progress').textContent(),'2 / 2줄 완료');await page.keyboard.press('Control+Shift+z');assert.equal(await page.locator('#progress').textContent(),'2 / 2줄 완료');await context.close();console.log('PASS keyboard shortcuts');
  assert.deepEqual(errors,[],'Browser errors / unexpected external requests');console.log('PASS no browser errors or external requests');
}finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));}})().catch(error=>{console.error(error);process.exitCode=1;});
